### ISSUE TITLE
Unicode error

### ISSUE THREAD

**Issue by jcc10** [alethiophile/ffmirror#1]
When trying to download this user: https://www.fanfiction.net/u/4294222/Elhini-Prime

Story 3 (https://www.fanfiction.net/s/11967471/3/Shadow-and-Light) returns the following error:

`Traceback (most recent call last):
  File "C:\Python34\lib\runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Python34\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Python34\lib\ffmirror\__main__.py", line 151, in <module>
    actions[pn]()
  File "C:\Python34\lib\ffmirror\__main__.py", line 118, in run_add
    download_list(**args.__dict__)
  File "C:\Python34\lib\ffmirror\__main__.py", line 108, in download_list
    cur_mirror.update_list(nsl, callback=progress)
  File "C:\Python34\lib\ffmirror\mirror.py", line 116, in update_list
    mod.compile_story(i, toc, out, contents=True, callback=callback)
  File "C:\Python34\lib\ffmirror\ffnet.py", line 182, in compile_story
    outfile.write(text + "\n\n")
  File "C:\Python34\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u014d' in position 6343: character maps to <undefined>`

I think this is due to non-English characters, is there any way to fix this?

The following is the source of the issue:
"Qui vállë tóquetë, ván tecë (If no review comes from y'all; no story comes from me)
Máriessë ar mára tecië"

**Comment by jcc10** [comment]
It seems that it's not getting the codec for the webpage / file it's saving, [this](https://stackoverflow.com/questions/16346914/python-3-2-unicodeencodeerror-charmap-codec-cant-encode-character-u2013-i) StackOverflow question might help. I just don't know where the code I need to edit is. I might search for it tomorrow.

**Comment by alethiophile** [comment]
This fic works when I run it. Therefore, it's likely a problem of the system encoding being different on your system. The line of code you want to edit will be line 178 in `mirror.py`; while currently no `encoding` parameter is passed to the `open` call, meaning it uses the system encoding, you could fix the problem by forcing an encoding which can map those characters. `encoding='utf-8'` would be the obvious value.

I'm not sure if this will work instantly, because if your system encoding isn't a variant on UTF-8, it raises the question of whether your system can read that easily. I have no experience with systems on non-UTF-8 encodings, so can't offer advice there. However, you could try running with this patch:

```
--- a/mirror.py
+++ b/mirror.py
@@ -175,7 +175,7 @@
             if callback: callback(n, (i, toc))
             fn = os.path.join(self.mirror_dir, story_file(md, self.use_ids))
             os.makedirs(os.path.split(fn)[0], exist_ok=True)
-            with open(fn, 'w') as out:
+            with open(fn, 'w', encoding='utf-8') as out:
                 mod.compile_story(md, toc, out, contents=True, callback=callback)

     def update_tags(self, sl):
```

Currently my development copy is divergent from the repo head in various ways, so I won't commit this yet. (I'm not sure if it's really the right answer anyway; if the system encoding can't encode the characters, it may be a band-aid.)

**Comment by jcc10** [comment]
That's what a dev branch is for. 😄 

I did the relevant patch but in the main.py
`with open(fn, 'w', encoding="utf8") as outfile:`
`with open(fn, 'w', encoding="utf-8") as outfile:`
`with open(fn, 'w', "utf-8") as outfile:`

None worked.

I hate windows 10... Well, time to set up a Linux VM to download the fanfictions.
